/**
 * Proves the embedded app cannot restyle the page it is embedded in.
 *
 * The vitest guard reads md2.css and rejects unscoped selectors; this is the same claim as a
 * browser sees it, with the real component mounted and the real cascade resolved. Both are worth
 * having: the guard catches a bad selector the moment it is written, this catches everything a
 * selector grep cannot — an inherited font, a `*` reset, a rule reaching out through a portal.
 *
 * The check is attribution, not a diff: it asks the browser which stylesheet supplies each
 * declaration on the host's own elements, and fails when the answer is one of ours. A plain
 * before/after comparison would fail on `@mat3ra/wave.js`, whose `dist/index.js` imports a
 * stylesheet that sets `body { font-family; margin; overflow: hidden }` — a leak that predates
 * MD 2.0 (v1's ThreeDEditorFullscreen imports the same module), is not ours to fix from here, and
 * would drown out the regression this exists to catch. Those are reported, not asserted.
 *
 * Usage:  npm start
 *         node tests/playwright/host-leak.mjs
 *         MD2_FROM=dist node tests/playwright/host-leak.mjs   # after `npm run transpile`
 *
 * `MD2_FROM=dist` renders the transpiled container out of dist/ through the package's own entry
 * point, which is the resolution web-app performs — the one that proves `copy-css` put md2.css
 * where `dist/embed/MaterialsDesignerContainer.js` expects it.
 */
import { chromium } from "playwright";

const BASE = process.env.MD2_BASE ?? "http://localhost:3001";
const PAGE = process.env.MD2_FROM === "dist" ? "host-dist.html" : "host.html";
const HOST = `${BASE}/tests/playwright/host-page/${PAGE}`;
/** The host's own elements. Nothing of ours may style any of them. */
const HOST_NODES = ["html", "body", "#host-panel", "#host-heading", "#host-button", "#host-input", "#host-kbd"];

const results = [];
function check(name, ok, detail = "") {
    results.push({ name, ok, detail });
    console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? ` — ${detail}` : ""}`);
}

const executablePath = process.env.MD2_CHROMIUM || undefined;
const browser = await chromium.launch({
    ...(executablePath ? { executablePath } : {}),
    args: ["--no-sandbox", "--use-gl=swiftshader"],
});
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));

const cdp = await page.context().newCDPSession(page);
await cdp.send("DOM.enable");
await cdp.send("CSS.enable");

await page.goto(HOST, { waitUntil: "networkidle" });
await page.waitForFunction(() => window.MD_EMBED_READY === true, { timeout: 60000 });
await page.waitForSelector(".md2-app", { timeout: 30000 });
await page.waitForTimeout(2500); // the GL scene, and any late stylesheet

check(`the embed mounted inside the host page (${PAGE})`, await page.locator(".md2-app").isVisible());
const appBg = await page.evaluate(
    () => getComputedStyle(document.querySelector(".md2-app")).backgroundColor,
);
check(
    "the app paints itself, so a host page's ground never shows through",
    appBg === "rgb(10, 18, 32)",
    appBg,
);
check(
    "the host's page background is still the host's",
    (await page.evaluate(() => getComputedStyle(document.body).backgroundColor)) ===
        "rgb(250, 235, 215)",
);

// --- attribution -----------------------------------------------------------
const texts = new Map();
async function sheetText(id) {
    if (!texts.has(id)) {
        const { text } = await cdp.send("CSS.getStyleSheetText", { styleSheetId: id });
        texts.set(id, text);
    }
    return texts.get(id);
}
/** Ours if it carries the app's class prefix or the generated token marker. */
const isOurs = (text) => /\.md2-|@generated by src\/kit\/theme\/tokens\.ts/.test(text);

const { root } = await cdp.send("DOM.getDocument", { depth: -1 });
const ours = [];
const foreign = [];
for (const selector of HOST_NODES) {
    const { nodeId } = await cdp.send("DOM.querySelector", { nodeId: root.nodeId, selector });
    const { matchedCSSRules = [] } = await cdp.send("CSS.getMatchedStylesForNode", { nodeId });
    for (const { rule } of matchedCSSRules) {
        // The page's own <style> is the harness, and the UA sheet is the browser's.
        if (rule.origin !== "regular" || !rule.styleSheetId) continue;
        const text = await sheetText(rule.styleSheetId);
        if (/#host-panel/.test(text)) continue;
        const decls = rule.style.cssProperties
            .filter((prop) => prop.text)
            .map((prop) => prop.text)
            .join(" ");
        (isOurs(text) ? ours : foreign).push(`${selector} ← ${rule.selectorList.text} { ${decls} }`);
    }
}

check(
    "no rule of ours reaches the host's own elements",
    ours.length === 0,
    ours.join("; ") || undefined,
);
if (foreign.length) {
    console.log(`\nNOTE  third-party rules reaching the host (not ours, and present in v1 too):`);
    foreign.forEach((f) => console.log(`      ${f}`));
}

// --- nothing of ours escapes the wrapper ----------------------------------
// The tokens now hang off `.md2-app` rather than `:root`, so anything of ours rendered outside
// that wrapper — a portalled menu, a dialog mounted on document.body — would lose its variables
// and render unstyled. Exercise the two surfaces most likely to portal, then check.
await page.getByTestId("open-catalog").click();
await page.waitForSelector(".md2-catalog", { timeout: 10000 });
const strays = await page.evaluate(() => {
    const app = document.querySelector(".md2-app");
    return [...document.querySelectorAll('[class*="md2-"]')]
        .filter((el) => el !== app && !app.contains(el))
        .map((el) => el.className)
        .slice(0, 5);
});
check("every element of ours renders inside .md2-app", strays.length === 0, strays.join("; "));
const unresolved = await page.evaluate(() =>
    [...document.querySelectorAll('[class*="md2-"]')].filter(
        (el) => !getComputedStyle(el).getPropertyValue("--bg1").trim(),
    ).length,
);
check("every element of ours resolves its tokens", unresolved === 0, `${unresolved} without --bg1`);

check("no uncaught page errors", errors.length === 0, errors.slice(0, 3).join(" | "));

await browser.close();
const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
process.exit(failed.length ? 1 : 0);
