version: "3.8"

services:
  materials-designer:
    image: materials-designer:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src/:/opt/app/src/
      - ./entrypoint.sh:/opt/app/entrypoint.sh
  # Meant to be used for CI/CD testing
  materials-designer-test:
    image: materials-designer-test:${IMAGE_TAG}
    build:
      args:
        BASE_TAG: ${IMAGE_TAG}
      context: .
      dockerfile: ./dockerfiles/app/test/Dockerfile
    depends_on:
      - materials-designer
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT}" ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - ./tests/cypress:/opt/test/cypress
      - ./entrypoint.sh:/opt/test/entrypoint.sh
