version: "3.8"

services:
  materials-designer:
    image: materials-designer:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src/:/opt/app/src/
      - ./entrypoint.sh:/opt/app/entrypoint.sh

  materials-designer-test:
    image: ghcr.io/exabyte-io/centos-7.9-node-8.11.4-chimp-xvfb-x11vnc-chrome_amd64:latest
    ports:
      - 5999:5999
    build:
      args:
        BASE_TAG: ${IMAGE_TAG}
      context: .
      dockerfile: ./dockerfiles/app/test/Dockerfile
    depends_on:
      - materials-designer
    volumes:
      - ./tests/cucumber/:/opt/test/tests/cucumber/
      - ./entrypoint.sh:/opt/test/entrypoint.sh
      - ./tests/.screenshots:/opt/test/.screenshots
