name: Build docker containers and run tests
description: Building docker images using ECR or github containers

runs:
  using: composite
  steps:
    - name: Build application container
      uses: ./actions/docker/build
      with:
        image-name: materials-designer
        dockerfile: ./dockerfiles/app/Dockerfile
        cli-args: --build-arg BASE_IMAGE=node


    - name: Build test container
      uses: ./actions/docker/build
      with:
        image-name: materials-designer-test
        dockerfile: ./dockerfiles/app/test/Dockerfile
        cli-args: --build-arg BASE_IMAGE=ghcr.io/exabyte-io/centos-7.9-node-8.11.4-chimp-xvfb-x11vnc-chrome_x86_64


    - name: Run tests
      shell: bash -l {0}
      run: |
        docker run -d -p 3001:3001 --name=materials-designer materials-designer:latest
        
        docker run --network=host materials-designer-test
