name: Build docker containers and run tests

runs:
  using: composite
  steps:
    - name: Build application container
      shell: bash -l {0}
      run: docker-compose build materials-designer

    - name: Build test container
      shell: bash -l {0}
      run: docker-compose build materials-designer-test

    - name: Run tests
      shell: bash -l {0}
      run: |
        docker-compose up -d materials-designer
        while ! docker logs materials-designer_materials-designer_1 2>&1 | grep "Compiled"; do
            failed=$(docker logs materials-designer_materials-designer_1 2>&1 | grep "Failed")
            if [[ "$failed" != "" ]]; then
                exit 1
            fi
            sleep 5
        done
        docker-compose run materials-designer-test
