name: Build docker containers and run tests
description: Building docker images using ECR or github containers

runs:
  using: composite
  steps:

#    TODO: figure out how to use cache properly
#    - name: Cache Docker images.
#      uses: ScribeMD/docker-cache@0.3.6
#      with:
#        key: docker-${{ runner.os }}-${{ hashFiles('package.json') }}

    - name: Build application container
      uses: ./actions/docker/build
      with:
        image-name: materials-designer
        image-tag: latest
        dockerfile: ./dockerfiles/app/Dockerfile
        cli-args: --build-arg BASE_IMAGE=node

#    - name: Push updated application container
#      shell: bash -l {0}
#      run: |
#        docker push ghcr.io/exabyte-io/materials-designer_x86_64:latest

    - name: Build test container
      uses: ./actions/docker/build
      with:
        image-name: materials-designer-test
        dockerfile: ./dockerfiles/app/test/Dockerfile
        cli-args: --build-arg BASE_IMAGE=node

    - name: Run tests
      shell: bash -l {0}
      run: |
        docker run -d -p 3001:3001 --name=materials-designer materials-designer:latest
        while ! docker logs materials-designer 2>&1 | grep "Compiled"; do
            failed=$(docker logs materials-designer 2>&1 | grep "Failed")
            if [[ "$failed" != "" ]]; then
                # print logs to understand what went wrong
                docker logs materials-designer 2>&1
                exit 1
            fi
            sleep 5
        done
        docker run --network=host materials-designer-test
