name: Build docker containers and run tests
description: Building docker images using ECR or github containers

runs:
  using: composite
  steps:
    - name: Pull existing image for the application container
      shell: bash -l {0}
      run: |
        docker pull ghcr.io/exabyte-io/materials-designer_x86_64

    - name: Build application container
      uses: ./actions/docker/build
      with:
        image-name: ghcr.io/exabyte-io/materials-designer_x86_64
        dockerfile: ./dockerfiles/app/Dockerfile
        cli-args: --build-arg BASE_IMAGE=node

    - name: Push updated application container
      shell: bash -l {0}
      run: |
        docker push ghcr.io/exabyte-io/materials-designer_x86_64

    - name: Build test container
      uses: ./actions/docker/build
      with:
        image-name: materials-designer-test
        dockerfile: ./dockerfiles/app/test/Dockerfile
        cli-args: --build-arg BASE_IMAGE=ghcr.io/exabyte-io/centos-7.9-node-8.11.4-chimp-xvfb-x11vnc-chrome_x86_64

    - name: Run tests
      shell: bash -l {0}
      run: |
        docker run -d -p 3001:3001 --name=materials-designer materials-designer:latest
        while ! docker logs materials-designer 2>&1 | grep "Compiled"; do
            failed=$(docker logs materials-designer 2>&1 | grep "Failed")
            if [[ "$failed" != "" ]]; then
                # print logs to understand what went wrong
                docker logs materials-designer 2>&1
                exit 1
            fi
            sleep 5
        done
        docker run --network=host materials-designer-test
