#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ">>>>>>>> Husky Pre-commit: Fixing lint"
echo ""
npm run lint:fix

echo ">>>>>>>> Husky Pre-commit: Transpiling sources"
echo ""
npm run transpile
npm run transpile-tests
git status

echo ">>>>>>>> Husky Pre-commit: Adding transpiled sources in dist"
echo ""
git add dist
echo ""
