name: Continuous Testing and Automated NPM Publication

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
            lfs: true

      - name: Docker build and test
        uses: ./.github/workflows/docker-build-test

  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          verify-tests: false
