name: CICD

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Build application container
        shell: bash -l {0}
        run: docker build -t materials-designer:centos -f dockerfiles/centos/Dockerfile .

      - name: Build test container
        shell: bash -l {0}
        run: docker build -t materials-designer:test -f dockerfiles/test/Dockerfile .

      - name: Run tests
        shell: bash -l {0}
        run: |
          docker run -p 3001:3001 -d materials-designer:centos
          sleep 30
          docker run --network=host materials-designer:test


  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Build application container
        shell: bash -l {0}
        run: docker build -t materials-designer:centos -f dockerfiles/centos/Dockerfile .

      - name: Build test container
        shell: bash -l {0}
        run: docker build -t materials-designer:test -f dockerfiles/test/Dockerfile .

      - name: Run tests
        shell: bash -l {0}
        run: |
          docker run -p 3001:3001 -d materials-designer:centos
          sleep 30
          docker run --network=host materials-designer:test

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
