name: Continuous Testing and Automated NPM Publication

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
            lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Validate JS package
        uses: ./actions/js/validate
        with:
          node-version: 12.21.x

      - name: Docker build and test
        uses: ./.github/workflows/docker-build-test
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}

      - name: Validate app dockerfile
        uses: ./actions/docker/validate
        with:
          dockerfile: ./dockerfiles/app/Dockerfile

      - name: Validate test dockerfile
        uses: ./actions/docker/validate
        with:
          dockerfile: ./dockerfiles/app/test/Dockerfile

  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          verify-tests: false
